name: pre-commit

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Or 3.x

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install pre-commit
        run: uv pip install pre-commit

      - name: Run pre-commit
        env:
          PRE_COMMIT_USE_UV: "1"
        run: pre-commit run --all-files --show-diff-on-failure
