name: Lint Code with Black and isort

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Or 3.x

      - name: Install dependencies
        run: |
          pip install black isort

      - name: Run Black (format code)
        run: |
          black . --verbose

      # - name: Run isort (check only)
      # run: |
      # isort --check-only .

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Apply black formatting"
          git push
